spring:
  datasource:
    url: jdbc:mysql://123.206.74.129:3306/mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver		

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  jackson:
    serialization:
      indent-output: true
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    
  http:
    multipart:
      max-file-size: 5Mb
  
  jmx:
    enabled: false

server:
  port: 8080
  context-path: /admin
  
fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:
    width: 150
    height: 150
  trackerList:
    - 123.206.74.129:22122
    
file.path.prefix: http://123.206.74.129:84/